[project]
name = "voyager"
version = "1.17.4"
description = "Package manager for C/C++ software"
readme = "Readme.md"
requires-python = "==3.10.*"
dependencies = [
    "click==8.1.7",
    "dohq-artifactory==0.10.1",
    "jsonschema==4.23.0",
    "node-semver==0.7.0",
    "platformdirs>=4.3.6",
    "voyager-plugin-list",
]

[tool.uv.sources]
voyager-plugin-list = { workspace = true }

[tool.uv.workspace]
members = ["plugins/voyager_listplugins"]

[project.scripts]
voyager = "voyager:voyager.main"

[tool.uv]
dev-dependencies = [
    "mypy>=1.19.1",
    "pyinstaller>=6.10.0",
    "types-jsonschema>=4.25.1.20251009",
    "types-requests>=2.32.4.20250913",
]

[[tool.mypy.overrides]]
module = ["semver.*", "artifactory.*", "voyager_plugins.*"]
follow_untyped_imports = true

[build-system]
requires = ["hatchling==1.26.3"]
build-backend = "hatchling.build"
